### ISSUE TITLE
Semicolon breaks query execution

### ISSUE THREAD

**Issue by alexschwarz89** [OXID-eSales/module_skeleton_generator#3]
The `_dbEvent` function does separate queries by simply using `explode` based on `;`. If there is any semicolon inside your query, for example let's say a description containing "`&nbsp;`", the query will fail and module activation does not throw any error.

I would suggest replacing
`$aSql = (array) explode(';', $sSql);` 

with a regular expression like
`$aSql = (array) preg_split("/;\n/", $sSql);`

and include a comment that queries must be separated with newlines.

Feel free to improve.

**Comment by Sieg** [comment]
Hi @alexschwarz89, could you please describe in more detail, how do you use it to reproduce the issue? Or maybe there is a bug entry created, please link it.

**Comment by Sieg** [comment]
Hi @alexschwarz89, Thaks for the fix! I have committed your suggested code with a small change, but in general, for new modules, using migrations would be a better option i believe.
